# Generated by Django 4.2.19 on 2025-02-18 14:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

  dependencies = [
    ("files", "0001_initial"),
  ]

  operations = [
    migrations.RenameIndex(
      model_name="file",
      new_name="files_file_content_adaf85_idx",
      old_name="files_file_content_idx",
    ),
    migrations.RenameIndex(
      model_name="file",
      new_name="files_file_user_id_160301_idx",
      old_name="files_file_user_idx",
    ),
    migrations.RenameIndex(
      model_name="file",
      new_name="files_file_session_266096_idx",
      old_name="files_file_session_idx",
    ),
    migrations.AlterField(
      model_name="file",
      name="id",
      field=models.UUIDField(
        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
      ),
    ),
  ]
